Prueba05Inventory/Controllers/ComponentTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Prueba05Inventory.Datos;

namespace Prueba05Inventory.Controllers
{
    public class ComponentTypeController : Controller
    {
        #region Contexto
        //Atributo contexto
        private inventoryfactorv3Entities _contexto;

        //Propiedad contexto
        public inventoryfactorv3Entities Contexto
        {
            set { _contexto = value; }
            get
            {
                if (_contexto == null)
                    _contexto = new inventoryfactorv3Entities();
                return _contexto;
            }
        }
        #endregion
        // GET: TypeComponent
        [Authorize]
        public ActionResult Index()
        {
            return View(Contexto.TipoComponente.ToList().AsEnumerable());
        }

        [Authorize]
        public ActionResult CrearTipo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CrearTipo(TipoComponente newTypeComponent)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Contexto.TipoComponente.Add(newTypeComponent);
                    Contexto.SaveChanges();

                    ViewBag.Estado = 1;
                    return View();
                }
                return View(newTypeComponent);
            }
            catch
            {
                ViewBag.Estado = 2;
                return View();
            }
        }

        [Authorize]
        public ActionResult ModificarTipo(int? id)
        {
            //Si el ID es nulo
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            //Buscar el tipo a editar
            TipoComponente CategoriaEditar = Contexto.TipoComponente.Find(id);

            //Si entidad es NULO (tipo no existe)
            if (CategoriaEditar == null)
                return HttpNotFound();

            //envia el tipo a editar a la vista

            return View(CategoriaEditar);
        }
        [HttpPost]
        public ActionResult ModificarTipo(TipoComponente TypeUpdate)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //Graba los cambios del tipo
                    Contexto.Entry(TypeUpdate).State = System.Data.Entity.EntityState.Modified;
                    Contexto.SaveChanges();

                    ViewBag.Estado = 1;
                    return View();
                }
                
                //Muestra la vista con los datos ingresados
                return View(TypeUpdate);
            }
            catch
            {
                ViewBag.Estado = 2;
                //Muestra la vista vacia
                return View();
            }
        }

        public ActionResult EliminarTipo(int? id, TipoComponente type)
        {
            try
            {
                TipoComponente TipoEliminar = new TipoComponente();
                if (ModelState.IsValid)
                {
                    if (id == null)
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                    //Buscar el tipo a editar
                    TipoEliminar = Contexto.TipoComponente.Find(id);

                    //Si entidad es NULO (tipo no existe)
                    if (TipoEliminar == null)
                        return HttpNotFound();

                    //Elimina el tipo
                    Contexto.TipoComponente.Remove(TipoEliminar);
                    Contexto.SaveChanges();
                }
                return Redirect("/ComponentType/Index");
            }
            catch
            {
                return Redirect("Index");
            }
        }
    }
}

Prueba05Inventory/Views/ComponentType/CrearTipo.cshtml
@{
    ViewBag.Title = "CreateTypeComponent";
    Layout = "~/Views/XLayout/_LayoutHome.cshtml";
}

<h1 class="h3 mb-4 text-gray-800">Crear Tipo</h1>

<div class="card">
    <div class="card-body md-4">
        <form action="CrearTipo" method="post">
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label for="inputtext">Tipo</label>
                    <input type="text" class="form-control" id="inputEmail4" name="tipo" required="required">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Crear</button>
            <a href="Index" class="btn btn-primary">Cancelar</a>
        </form>
    </div>
</div>

@section Mensajes {
    <script type="text/javascript">
        if (@ViewBag.Estado == 1) {
            alertify.success('Tipo creado correctamente!');
        } else {
            alertify.error('Error al crear el Tipo');
        }
    </script>
}

Prueba05Inventory/Views/ComponentType/Index.cshtml
@model IEnumerable<Prueba05Inventory.Datos.TipoComponente>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/XLayout/_LayoutHome.cshtml";
}

<!-- Page Heading -->
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h1 class="h3 mb-2 text-gray-800">Tipos de Componentes</h1>
    </div>
    <div class="card-body">
        <div class="table-responsive">

            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>Categoria</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.tipo)
                        </td>

                        <td>
                            <a href="@Url.Action("ModificarTipo", "ComponentType", new { id = item.tipo_componente_id })" class="btn btn-primary btn-icon-split btn-sm">
                                <span class="icon text-white-50">
                                    <i class="fas fa-flag"></i>
                                </span>
                                <span class="text">Editar</span>
                            </a>
                            <a href="@Url.Action("EliminarTipo", "ComponentType", new { id = item.tipo_componente_id })" class="btn btn-danger btn-icon-split btn-sm">
                                <span class="icon text-white-50">
                                    <i class="fas fa-trash"></i>
                                </span>
                                <span class="text">Eliminar</span>
                            </a>
                        </td>

                    </tr>
                }
            </table>

        </div>
    </div>
</div>

Prueba05Inventory/Views/ComponentType/ModificarTipo.cshtml
@model Prueba05Inventory.Datos.TipoComponente
@{
    ViewBag.Title = "UpdateTypeComponent";
    Layout = "~/Views/XLayout/_LayoutHome.cshtml";
}

<h1 class="h3 mb-4 text-gray-800">Actualizar Tipo</h1>

<div class="card">
    <div class="card-body md-4">
        @using (Html.BeginForm())
        {
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label for="inputtext">Tipo</label>
                    @Html.HiddenFor(model => model.tipo_componente_id)
                    @Html.EditorFor(model => model.tipo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Actualizar</button>
            <a href="/ComponentType/Index" class="btn btn-primary">Cancelar</a>
        }
    </div>
</div>

@section Mensajes {
    <script type="text/javascript">
        if (@ViewBag.Estado == 1) {
            alertify.success('Tipo modificado correctamente!');
        } else {
            alertify.error('Error al modificar el Tipo');
        }
    </script>
}