Prueba05Inventory/Controllers/ComponentCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Prueba05Inventory.Datos;

namespace Prueba05Inventory.Controllers
{
    public class ComponentCategoryController : Controller
    {
        #region Contexto
        //Atributo contexto
        private inventoryfactorv3Entities _contexto;

        //Propiedad contexto
        public inventoryfactorv3Entities Contexto
        {
            set { _contexto = value; }
            get
            {
                if (_contexto == null)
                    _contexto = new inventoryfactorv3Entities();
                return _contexto;
            }
        }
        #endregion
        // GET: CategoryComponent
        [Authorize]
        public ActionResult Index()
        {
            return View(Contexto.CategoriaComponente.ToList().AsEnumerable());
        }

        [Authorize]
        public ActionResult CrearCategoria()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CrearCategoria(CategoriaComponente newCategory)
        {
            try
            {
                //validamos los datos ingresados
                if (ModelState.IsValid)
                {
                    //registramos la nueva categoria
                    Contexto.CategoriaComponente.Add(newCategory);
                    Contexto.SaveChanges();
                    //llamamos al metodo Index
                    ViewBag.Estado = 1;
                    return View();
                    //muestra la vista "create" con datos ingresados
                }
                return View(newCategory);
            }
            catch
            {
                ViewBag.Estado = 2;
                //Muestra la vista "create" vacia
                return View();
            }
        }

        [Authorize]
        public ActionResult ModificarCategoria(int? id)
        {
            //Si el ID es nulo
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            //Buscar la categoria a editar
            CategoriaComponente CategoriaEditar = Contexto.CategoriaComponente.Find(id);

            //Si entidad es NULO (categoria no existe)
            if (CategoriaEditar == null)
                return HttpNotFound();

            //envia la categoria a editar a la vista
            return View(CategoriaEditar);
        }
        [HttpPost]
        public ActionResult ModificarCategoria(int? id, CategoriaComponente CategoryEdit)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //Graba los cambios en la categoria
                    Contexto.Entry(CategoryEdit).State = System.Data.Entity.EntityState.Modified;
                    Contexto.SaveChanges();

                    ViewBag.Estado = 1;
                    return View();
                }
                //Muestra la vista con los datos ingresados
                return View(CategoryEdit);
            }
            catch (Exception ex)
            {
                ViewBag.Estado = 2;
                @ViewBag.Nombre = ex;
                //Muestra la vista vacia
                return View();
            }
        }

        public ActionResult EliminarCategoria(int? id, CategoriaComponente category)
        {
            try
            {
                CategoriaComponente CategoriaEliminar = new CategoriaComponente();
                if (ModelState.IsValid)
                {
                    if (id == null)
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                    //Buscar la categoria a editar
                    CategoriaEliminar = Contexto.CategoriaComponente.Find(id);

                    //Si entidad es NULO (categoria no existe)
                    if (CategoriaEliminar == null)
                        return HttpNotFound();

                    //Elimina la categoria
                    Contexto.CategoriaComponente.Remove(CategoriaEliminar);
                    Contexto.SaveChanges();
                }
                return Redirect("/ComponentCategory/Index");
            }
            catch
            {
                return Redirect("Index");
            }
        }
    }
}

Prueba05Inventory/Views/ComponentCategory/CrearCategoria.cshtml
@{
    ViewBag.Title = "CreateCategoryComponent";
    Layout = "~/Views/XLayout/_LayoutHome.cshtml";
}

<h1 class="h3 mb-4 text-gray-800">Crear Categoria</h1>

<div class="card">
    <div class="card-body md-4">
        <form action="CrearCategoria" method="post">
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label for="inputtext">Categoria</label>
                    <input type="text" class="form-control" id="inputEmail4" name="categoria" required="required">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Crear</button>
            <a href="Index" class="btn btn-primary">Cancelar</a>
        </form>
    </div>
</div>

@section Mensajes {
    <script type="text/javascript">
        if (@ViewBag.Estado == 1) {
            alertify.success('Categoria creada correctamente!');
        } else {
            alertify.error('Error al crear la Categoria');
        }
    </script>
}

Prueba05Inventory/Views/ComponentCategory/Index.cshtml
@model IEnumerable<Prueba05Inventory.Datos.CategoriaComponente>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/XLayout/_LayoutHome.cshtml";
}

<!-- Page Heading -->
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h1 class="h3 mb-2 text-gray-800">Categorias de Componentes</h1>
    </div>
    <div class="card-body">
        <div class="table-responsive">

            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>Categoria</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.categoria)
                        </td>

                        <td>
                            <a href="@Url.Action("ModificarCategoria", "ComponentCategory", new { id = item.categoria_componente_id })" class="btn btn-primary btn-icon-split btn-sm">
                                <span class="icon text-white-50">
                                    <i class="fas fa-flag"></i>
                                </span>
                                <span class="text">Editar</span>
                            </a>
                            <a href="@Url.Action("EliminarCategoria", "ComponentCategory", new { id = item.categoria_componente_id })" class="btn btn-danger btn-icon-split btn-sm">
                                <span class="icon text-white-50">
                                    <i class="fas fa-trash"></i>
                                </span>
                                <span class="text">Eliminar</span>
                            </a>
                        </td>

                    </tr>
                }
            </table>

        </div>
    </div>
</div>

Prueba05Inventory/Views/ComponentCategory/ModificarCategoria.cshtml
@model Prueba05Inventory.Datos.CategoriaComponente
@{
    ViewBag.Title = "UpdateCategoryComponent";
    Layout = "~/Views/XLayout/_LayoutHome.cshtml";
}

<h1 class="h3 mb-4 text-gray-800">Actualizar Categoria @ViewBag.Nombre</h1>

<div class="card">
    <div class="card-body md-4">
        @using (Html.BeginForm())
        {
            <div class="form-row">
                <div class="form-group col-md-4">
                    @Html.HiddenFor(model => model.categoria_componente_id)
                    @Html.EditorFor(model => model.categoria, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.categoria)
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Actualizar</button>
            <a href="/ComponentCategory/Index" class="btn btn-primary">Cancelar</a>
        }
    </div>
</div>

@section Mensajes {
    <script type="text/javascript">
        if (@ViewBag.Estado == 1) {
            alertify.success('Categoria modificada correctamente!');
        } else {
            alertify.error('Error al modificar la Categoria');
        }
    </script>
}