Prueba05Inventory/Controllers/ComponentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Prueba05Inventory.Datos;
using Prueba05Inventory.Models;

namespace Prueba05Inventory.Controllers
{
    public class ComponentController : Controller
    {

        #region Contexto
        //Atributo contexto
        private inventoryfactorv3Entities _contexto;

        //Propiedad contexto
        public inventoryfactorv3Entities Contexto
        {
            set { _contexto = value; }
            get
            {
                if (_contexto == null)
                    _contexto = new inventoryfactorv3Entities();
                return _contexto;
            }
        }
        #endregion

        public ActionResult ListarComponente()
        {
            return View(Contexto.Componentes.ToList().AsEnumerable());
        }

        [Authorize]
        public ActionResult CrearComponente()
        {
            ListarCaracteristicasComponente();
            return View();
        }

        [HttpPost]
        public ActionResult CrearComponente(HttpPostedFileBase imagenComponente, Componentes componentes)
        {
            SubirImagen(imagenComponente, componentes);

            try
            {
                //validamos los datos ingresados
                if (ModelState.IsValid)
                {
                    //registramos el nuevo componente
                    Contexto.Componentes.Add(componentes);
                    Contexto.SaveChanges();

                    //llamamos al metodo Index
                    ViewBag.Estado = 1;
                    return View();
                    //muestra la vista con datos ingresados
                }
                return View();
            }
            catch
            {
                ViewBag.Estado = 2;
                //Muestra la vista vacia
                return View();
            }
        }

        [Authorize]
        public ActionResult ModificarComponente(int? id)
        {
            //Si el ID es nulo
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            //Buscar el componente a editar
            ListarCaracteristicasComponente();
            Componentes ComponenteEditar = Contexto.Componentes.Find(id);

            //Si entidad es NULO (componente no existe)
            if (ComponenteEditar == null)
                return HttpNotFound();

            InformacionComponentes info = new InformacionComponentes();
            info.componentes = ComponenteEditar;


            //envia el componente a editar a la vista
            return View(info);
        }

        [HttpPost]
        public ActionResult ModificarComponente(HttpPostedFileBase imagenComponente, Componentes componentes)
        {
            //return View();

            SubirImagen(imagenComponente, componentes);
            try
            {
                if (ModelState.IsValid)
                {
                    /**/

                    //Graba los cambios del componente
                    Contexto.Entry(componentes).State = System.Data.Entity.EntityState.Modified;
                    Contexto.SaveChanges();

                    ViewBag.Estado = 1;
                    return View();
                }
                
                //Muestra la vista con los datos ingresados
                return View(componentes);
            }
            catch
            {
                ViewBag.Estado = 2;
                //Muestra la vista vacia
                return View();
            }
        }

        public ActionResult EliminarComponente(int? id)
        {
            try
            {
                Componentes ComponenteEliminar = new Componentes();
                if (ModelState.IsValid)
                {
                    if (id == null)
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                    //Buscar el componente a editar
                    ComponenteEliminar = Contexto.Componentes.Find(id);

                    //Si entidad es NULO (componente no existe)
                    if (ComponenteEliminar == null)
                        return HttpNotFound();

                    //Elimina el componente
                    Contexto.Componentes.Remove(ComponenteEliminar);
                    Contexto.SaveChanges();
                    return Redirect("/Component/ListarComponente");
                }
                return View(ComponenteEliminar);
            }
            catch
            {
                return View();
            }
        }

        //Funcion para listar las caracteristicas del componente
        public void ListarCaracteristicasComponente()
        {
            ViewBag.TipoComponente = Contexto.TipoComponente.Select(x => new SelectListItem
            {
                Text = x.tipo,
                Value = x.tipo_componente_id.ToString()
            });

            ViewBag.CategoriaComponente = Contexto.CategoriaComponente.Select(x => new SelectListItem
            {
                Text = x.categoria,
                Value = x.categoria_componente_id.ToString()
            });
        }

        //Funcion para convertir la imagen subida
        public ActionResult ConvertirImagen(int? id)
        {
            var imagenComponente = Contexto.Componentes.Where(x => x.componente_id == id).FirstOrDefault();
            return File(imagenComponente.imagen, "image/jpeg");
        }

        //Funcion para subir la imagen a la base de datos
        public void SubirImagen(HttpPostedFileBase imagenComponente,  Componentes componentes)
        {
            ListarCaracteristicasComponente();
            if (imagenComponente != null && imagenComponente.ContentLength > 0)
            {
                byte[] imagenData = null;
                using (var binaryComponente = new BinaryReader(imagenComponente.InputStream))
                {
                    imagenData = binaryComponente.ReadBytes(imagenComponente.ContentLength);
                }
                componentes.imagen = imagenData;
            }
            else
            {
                var comp = (from co in Contexto.Componentes
                            where co.componente_id == componentes.componente_id
                            select co.imagen).FirstOrDefault();

                componentes.imagen = comp;
            }
        }

    }
}

Prueba05Inventory/Views/Component/CrearComponente.cshtml
@model Prueba05Inventory.Models.InformacionComponentes
@{
    ViewBag.Title = "CrearComponente";
    Layout = "~/Views/XLayout/_LayoutHome.cshtml";
}

<!-- Page Heading -->
<h1 class="h3 mb-4 text-gray-800">Crear Componente</h1>
<div class="container">
    <div class="container">
        <div class="card">
            <div class="card-body md-4">
                @using (Html.BeginForm("CrearComponente", "Component", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputEmail4">Nombre</label>
                            @Html.EditorFor(model => model.componentes.nombre, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        </div>
                        <div class="form-group col-md-8">
                            <label for="inputPassword4">Descripcion</label>
                            @Html.EditorFor(model => model.componentes.descripcion, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputPassword4">Precio</label>
                            @Html.EditorFor(model => model.componentes.precio, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputPassword4">Tipo de componente</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="inputGroupSelect01">Tipo</label>
                                </div>
                                @Html.DropDownListFor(model => model.componentes.tipo_componente_id, (IEnumerable<SelectListItem>)ViewBag.TipoComponente, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputPassword4">Cantidad</label>
                            @Html.EditorFor(model => model.componentes.stock, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputPassword4">Categoria de componente</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="inputGroupSelect01">Tipo</label>
                                </div>
                                @Html.DropDownListFor(model => model.componentes.categoria_componente_id, (IEnumerable<SelectListItem>)ViewBag.CategoriaComponente, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-8">
                            <label for="exampleFormControlFile1">Cargar Imagen:</label>
                            <input type="file" class="form-control-file" name="imagenComponente" required="required">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Crear</button>
                    <a href="ListarComponente" class="btn btn-primary">Cancelar</a>
                }
            </div>
        </div>


    </div>
</div>

@section Mensajes {
    <script type="text/javascript">
        if (@ViewBag.Estado == 1) {
            alertify.success('Componente creado correctamente!');
        } else {
            alertify.error('Error al crear el Componente');
        }
    </script>
}

Prueba05Inventory/Views/Component/ListarComponente.cshtml
@model IEnumerable<Prueba05Inventory.Datos.Componentes>
@{
    ViewBag.Title = "ListarComponente";
    Layout = "~/Views/XLayout/_LayoutHome.cshtml";
}

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h1 class="h3 mb-2 text-gray-800">Componentes</h1>
    </div>
    <div class="card-body">
        <div class="table-responsive">

            <table class="table table-bordered" id="dataTable">
                <thead class="thead-dark">
                    <tr>
                        <th>Imagen</th>
                        <th>Nombre</th>
                        <th>Descripcion</th>
                        <th>Precio</th>
                        <th>Stock</th>
                        <th>Categoria</th>
                        <th>Tipo</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <img src="@Url.Action("ConvertirImagen","Component", new { id = item.componente_id })" width="80%" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.descripcion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.precio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.stock)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CategoriaComponente.categoria)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TipoComponente.tipo)
                        </td>

                        <td>
                            <a href="@Url.Action("ModificarComponente", "Component", new { id = item.componente_id })" class="btn btn-primary btn-icon-split btn-sm">
                                <span class="icon text-white-50">
                                    <i class="fas fa-flag"></i>
                                </span>
                                <span class="text">Editar</span>
                            </a>
                            <a href="@Url.Action("EliminarComponente", "Component", new { id = item.componente_id })" class="btn btn-danger btn-icon-split btn-sm">
                                <span class="icon text-white-50">
                                    <i class="fas fa-trash"></i>
                                </span>
                                <span class="text">Eliminar</span>
                            </a>
                        </td>

                    </tr>
                }
            </table>

        </div>
    </div>
</div>

Prueba05Inventory/Views/Component/ModificarComponente.cshtml
@model Prueba05Inventory.Models.InformacionComponentes
@{
    ViewBag.Title = "ModificarComponente";
    Layout = "~/Views/XLayout/_LayoutHome.cshtml";
}

<!-- Page Heading -->
<h1 class="h3 mb-4 text-gray-800">Modificar Componente</h1>
<div class="container">
    <div class="container">
        <div class="card">
            <div class="card-body md-4">
                @using (Html.BeginForm("ModificarComponente", "Component", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.HiddenFor(model => model.componentes.componente_id)
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputEmail4">Nombre</label>
                            @Html.EditorFor(model => model.componentes.nombre, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        </div>
                        <div class="form-group col-md-8">
                            <label for="inputPassword4">Descripcion</label>
                            @Html.EditorFor(model => model.componentes.descripcion, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputPassword4">Precio</label>
                            @Html.EditorFor(model => model.componentes.precio, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputPassword4">Tipo de componente</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="inputGroupSelect01">Tipo</label>
                                </div>
                                @Html.DropDownListFor(model => model.componentes.tipo_componente_id, (IEnumerable<SelectListItem>)ViewBag.TipoComponente, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="inputPassword4">Cantidad</label>
                            @Html.EditorFor(model => model.componentes.stock, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputPassword4">Categoria de componente</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="inputGroupSelect01">Tipo</label>
                                </div>
                                @Html.DropDownListFor(model => model.componentes.categoria_componente_id, (IEnumerable<SelectListItem>)ViewBag.CategoriaComponente, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-8">
                            <label for="exampleFormControlFile1">Cargar Imagen:</label>
                            <input type="file" class="form-control-file" name="imagenComponente">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Modificar</button>
                    <a href="/Component/ListarComponente" class="btn btn-primary">Cancelar</a>
                }
            </div>
        </div>


    </div>
</div>

@section Mensajes {
    <script type="text/javascript">
        if (@ViewBag.Estado == 1) {
            alertify.success('Componente modificado correctamente!');
        } else {
            alertify.error('Error al modificar el Componente');
        }
    </script>
}